fix: killing single etcd POD is ok. cluster with 3 PODs will recover. error was: POD was stuck at "etcd node was permanently removed." so etcd node could not re-join the cluster anymore. When re-joining cluster etcd node "forgot" it's member_id becuase directory /var/run/etcd was cleaned at shutdown, so file "member_id" was deleted. Subsequently etcd node tried to join the cluster as "new" node with an old and removed member_id hash.

diff --git a/stolon/charts/etcd/templates/statefulset.yaml b/stolon/charts/etcd/templates/statefulset.yaml
--- a/stolon/charts/etcd/templates/statefulset.yaml
+++ b/stolon/charts/etcd/templates/statefulset.yaml
@@ -63,12 +63,16 @@ spec:
                   }
 
                   echo "Removing ${HOSTNAME} from etcd cluster"
-
-                  ETCDCTL_ENDPOINT=${EPS} etcdctl member remove $(member_hash)
-                  if [ $? -eq 0 ]; then
+                  #echo "Removing ${HOSTNAME} from etcd cluster" > /var/run/etcd/stopping.log
+                  echo "NOT Removing ${HOSTNAME} from etcd cluster" > /var/run/etcd/stopping.log
+                  echo "ETCDCTL_ENDPOINT=${EPS}" > /var/run/etcd/stopping.log
+                  
+                  #ETCDCTL_ENDPOINT=${EPS} etcdctl member remove $(member_hash)
+                  #if [ $? -eq 0 ]; then
                       # Remove everything otherwise the cluster will no longer scale-up
-                      rm -rf /var/run/etcd/*
-                  fi
+                  #    rm -rf /var/run/etcd/*
+                  #    echo "Removed ${HOSTNAME} from etcd cluster and deleted directory contents." > /var/run/etcd/stopping.log
+                  #fi
         command:
           - "/bin/sh"
           - "-ec"
@@ -80,50 +84,91 @@ spec:
                 echo "collecting members ..."
                 while ! etcdctl member list &>/dev/null; do sleep 1; done
                 etcdctl member list | grep http://${HOSTNAME}.${PETSET_NAME}:2380 | cut -d':' -f1 | cut -d'[' -f1 > /var/run/etcd/member_id
-                echo "member_id: "
+                echo "member_id (collected): "
                 cat /var/run/etcd/member_id
+                echo "Datadir contents:"
+                ls -al /var/run/etcd
                 exit 0
             }
-
-            eps() {
-                EPS=""
-                for i in $(seq 0 $((${INITIAL_CLUSTER_SIZE} - 1))); do
-                    EPS="${EPS}${EPS:+,}http://${PETSET_NAME}-${i}.${PETSET_NAME}:2379"
-                done
-                echo ${EPS}
-            }
-
+ 
+            EPS=""
+            for i in $(seq 0 $((${INITIAL_CLUSTER_SIZE} - 1))); do
+              EPS="${EPS}${EPS:+,}http://${PETSET_NAME}-${i}.${PETSET_NAME}:2379"
+            done
+            echo "EPS=${EPS}"
+            
             member_hash() {
-                echo "calculating member hash."
+                # getting member hash for this address from "member list"
                 etcdctl member list | grep http://${HOSTNAME}.${PETSET_NAME}:2380 | cut -d':' -f1 | cut -d'[' -f1
             }
 
+            wait_for_datadir() {
+                set +e
+                while true; do
+                    echo "waiting for data-dir ..."
+                    DATA_DIR_AVAIL=$(df |grep /var/run/etcd$)
+                    if [ -n "${DATA_DIR_AVAIL}" ]; then
+                        break
+                    fi                    
+                    sleep 1s
+                done
+                echo "data-dir is now available."
+                set -e
+            }
+            
+            wait_for_datadir
+            
+            echo "Datadir contents:"
+            ls -al /var/run/etcd
+            
             # re-joining after failure?
             if [ -e /var/run/etcd/default.etcd ]; then
                 echo "Re-joining etcd member"
+                # TODO: what to do, when /var/run/etcd/member_id does not exist? Maybe delete /var/run/etcd/* like in a removal / stop ? see above.
+                set +e
                 member_id=$(cat /var/run/etcd/member_id)
-                echo "member id: ${member_id}"
+                set -e
                 
-                # re-join member
-                ETCDCTL_ENDPOINT=$(eps) etcdctl member update ${member_id} http://${HOSTNAME}.${PETSET_NAME}:2380
-                echo "Starting etcd"
-                exec etcd --name ${HOSTNAME} \
-                    --listen-peer-urls http://${HOSTNAME}.${PETSET_NAME}:2380 \
-                    --listen-client-urls http://${HOSTNAME}.${PETSET_NAME}:2379,http://127.0.0.1:2379 \
-                    --advertise-client-urls http://${HOSTNAME}.${PETSET_NAME}:2379 \
-                    --data-dir /var/run/etcd/default.etcd
+                if [ ! -n "${member_id}" ]; then
+                  echo "getting member_id from member_hash"
+                  member_id=$(member_hash)
+                fi
+                
+                if [ ! -n "${member_id}" ]; then
+                  echo "ERROR: Can't get member_id. NOT re-joining."
+                  # Remove everything otherwise the cluster will no longer scale-up
+                  rm -rf /var/run/etcd/*                  
+                else
+                  echo "member id (re-join): ${member_id}"
+                  # re-join member
+                  echo "re-joining: getting ETCDCTL_ENDPOINT."
+                  echo "ETCDCTL_ENDPOINT=${EPS}"
+                  set e+
+                  ETCDCTL_ENDPOINT=${EPS} etcdctl member update ${member_id} http://${HOSTNAME}.${PETSET_NAME}:2380
+                  set e-
+                  echo "Starting etcd"
+                  exec etcd --name ${HOSTNAME} \
+                      --listen-peer-urls http://${HOSTNAME}.${PETSET_NAME}:2380 \
+                      --listen-client-urls http://${HOSTNAME}.${PETSET_NAME}:2379,http://127.0.0.1:2379 \
+                      --advertise-client-urls http://${HOSTNAME}.${PETSET_NAME}:2379 \
+                      --data-dir /var/run/etcd/default.etcd
+                fi
+                
             fi
 
             # etcd-PET_ID
+            # TODO: PET_ID is not a number (instead it is ntrol-etcd-1)
             PET_ID=${HOSTNAME:5:${#HOSTNAME}}
+            echo "PET_ID=${PET_ID} INITIAL_CLUSTER_SIZE=${INITIAL_CLUSTER_SIZE}"
 
             # adding a new member to existing cluster (assuming all initial pets are available)
             if [ "${PET_ID}" -ge ${INITIAL_CLUSTER_SIZE} ]; then
-                export ETCDCTL_ENDPOINT=$(eps)
+                export ETCDCTL_ENDPOINT=${EPS}
 
                 # member already added?
                 MEMBER_HASH=$(member_hash)
                 if [ -n "${MEMBER_HASH}" ]; then
+                    echo "MEMBER_HASH is not empty. Removing member. MEMBER_HASH=${MEMBER_HASH}"
                     # the member hash exists but for some reason etcd failed
                     # as the datadir has not be created, we can remove the member
                     # and retrieve new hash
@@ -171,7 +216,7 @@ spec:
             collect_member &
 
             # join member
-            echo "Starting etcd. with HOSTNAME: ${HOSTNAME}, PETSET_NAME: ${PETSET_NAME}"
+            echo "Starting etcd. with HOSTNAME: ${HOSTNAME}, PETSET_NAME: ${PETSET_NAME}, PEERS: ${PEERS}"
             exec etcd --name ${HOSTNAME} \
                 --initial-advertise-peer-urls http://${HOSTNAME}.${PETSET_NAME}:2380 \
                 --listen-peer-urls http://${HOSTNAME}.${PETSET_NAME}:2380 \
